pub mod agent_task;
pub(crate) mod borrowck;
#[path = "project/build_contract.rs"]
pub mod build_contract;
pub mod codegen;
pub(crate) mod cranelift_backend;
pub mod dap;
pub mod diagnostic_catalog;
pub mod diagnostics;
pub mod doctor;
pub mod hir;
pub mod intent_ir;
pub mod json_contract;
pub mod lockfile;
pub mod lsp;
pub mod manifest;
pub mod mir;
pub mod new_project;
pub mod project;
pub mod registry;
pub mod stdlib;
pub mod syntax; pub mod transactional_workspace; pub mod verification_planner;
#[cfg(test)] #[path = "../tests/lib_unit.rs"] mod tests;
